### ISSUE TITLE
Does not extract all sounds from the game

### ISSUE THREAD

**Issue by Neinndall** [Fabien2S/DBDToolbox#4]
I have checked through another tool, and I don't see some like "mu_lobby_KXX"

**Comment by Fabien2S** [comment]
All the "large" sounds are not extracted, I did try a workaround yesterday but I need to test it

Hopefully I will push an update today!

**Comment by Fabien2S** [comment]
Update: The fix did extract the missing files, I just need to rename them
![image](https://user-images.githubusercontent.com/18100602/133586722-9c55d1bb-5a33-4eaf-85ae-2ac71cf8ad0f.png)

**Comment by Fabien2S** [comment]
Fixed in the new release!
https://github.com/Fabien2S/DBDToolbox/releases/tag/v2.2
