### ISSUE TITLE
Not work in the new versionn Unreal Engine 4.27!

### ISSUE THREAD

**Issue by Neinndall** [Fabien2S/DBDToolbox#9]
![234](https://user-images.githubusercontent.com/66384195/161823551-6bc5a4aa-023e-40eb-97fa-00826e70b5a1.PNG)

I guess it's because of the unreal engine change!
I post this error, for when you can take a look at it!

**Comment by Fabien2S** [comment]
Thanks for the report

The library that I'm reliying on is responsible for the crash: [UETools](https://github.com/UETools/UETools).
I'm pretty sure this exact library is also used to populate this repository: [DBDPakTrack](https://github.com/jesterret/DBDPakTrack).

For now, I'm just gonna wait to see if either of thoses repository get updated, as I don't really have time to learn how it works under the hood (nor the knowledge to be fair).

I will try to investigate a little more, and create an issue [here](https://github.com/UETools/UETools/issues)

**Comment by Neinndall** [comment]
Thx for the reply Fabien! ill wait for a hotfix!

**Comment by Neinndall** [comment]
Hi Fabian! Any advance? I hope you have a time to find the solution! Since there is version 6.0.0!
I don't know if you can keep me informed! Thank you very much!

**Comment by Fabien2S** [comment]
Sorry for the delay, I'm quite busy and don't have the time to look into it.

In the meantime, I saw that [FModel](https://github.com/iAmAsval/FModel) supports Wwise audio (which is used by DeadByDaylight), perhaps it can works?

**Comment by Neinndall** [comment]
Don't worry, I asked if you were already working on it! But I'm super interested since FModel doesn't relate and name the audio files like your tool does!
Yeah in Fmodel has support for wwise audio and I can play the audios, but it doesn't do the same job that your tool does, which is to match the audios with their corresponding names!

**Comment by Neinndall** [comment]
Excuse me... any news about the hotfix? It's been 4 months after the change of UE4.25 to 4.27, I don't know if you had time for it, I don't mean to hurry, just information :)

**Comment by Fabien2S** [comment]
To be honest, this will probably never be updated again
Or perhaps as a simple script to rename the sounds exported with FModel

But again, "when" is the big question, perhaps never

I don't really have any incentive to update it again, as I no longer play DBD anymore

**Comment by Neinndall** [comment]
My purpose is not to be annoying, but thank you very much for the answer!
Thank you very much for this wonderful tool :)
I will look for other ways.

**Comment by AndnixSH** [comment]
> Don't worry, I asked if you were already working on it! But I'm super interested since FModel doesn't relate and name the audio files like your tool does! Yeah in Fmodel has support for wwise audio and I can play the audios, but it doesn't do the same job that your tool does, which is to match the audios with their corresponding names!

How did you open audio? for me, its only opening json properties

**Comment by Fabien2S** [comment]
If you are still looking for a way to get the sounds, I just found this repository : https://github.com/Masusder/DBDSounds

**Comment by AndnixSH** [comment]
Sadly, there are no proper names in the extracted files

**Comment by Fabien2S** [comment]
There is! https://github.com/Masusder/DBDSounds/tree/main/Converted%20Files

**Comment by AndnixSH** [comment]
Ok, I was looking for music specifically, just realized it was located in SFX

**Comment by Neinndall** [comment]
> Ok, I was looking for music specifically, just realized it was located in SFX

In the end I made a tool since Fabien stopped updating it, you can go to --> https://github.com/Neinndall/DBDAudioRenamer in case you are interested in extracting the audio in SFX

**Comment by AndnixSH** [comment]
Thanks
